name: consumer-staples-forecast
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.11
  - pip
  - pip:
    - pandas==2.3.2
    - numpy==2.3.2
    - scikit-learn==1.7.1
    - xgboost==3.1.2
    - scipy==1.16.1
    - matplotlib==3.10.5
    - seaborn==0.13.2
    - yfinance