name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - anaconda-anon-usage=0.7.1=py312hfc0e8ea_100
  - annotated-types=0.6.0=py312h06a4308_1
  - anyio=4.10.0=pyhe01879c_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py312h4c3975b_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.5=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - boltons=25.0.0=py312h06a4308_0
  - brotli=1.1.0=hb9d3cd8_3
  - brotli-bin=1.1.0=hb9d3cd8_3
  - brotlicffi=1.0.9.2=py312hbdd6827_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py312h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - conda=25.5.1=py312h06a4308_0
  - conda-anaconda-telemetry=0.2.0=py312h06a4308_1
  - conda-anaconda-tos=0.2.1=py312h06a4308_1
  - conda-content-trust=0.2.0=py312h06a4308_1
  - conda-libmamba-solver=25.4.0=pyhdf14ebd_1
  - conda-package-handling=2.4.0=py312h06a4308_1
  - conda-package-streaming=0.12.0=py312h06a4308_1
  - contourpy=1.3.3=py312hd9148b4_1
  - cpp-expected=1.1.0=hdb19cb5_0
  - cryptography=45.0.3=py312h2ccb017_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dbus=1.16.2=h3c4dab8_0
  - debugpy=1.8.16=py312hbdd6827_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distro=1.9.0=py312h06a4308_0
  - double-conversion=3.3.1=h5888daf_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - fmt=11.2.0=h07f6e7f_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.59.1=py312h8a5da7c_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.13.3=ha770c72_1
  - frozendict=2.4.2=py312h06a4308_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - graphite2=1.3.14=hecca717_2
  - h11=0.16.0=py312h06a4308_1
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.4.3=h15599e2_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=py312h06a4308_1
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.7=py312h06a4308_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=9.4.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpatch=1.33=py312h06a4308_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-collaboration=4.1.0=pyhe01879c_0
  - jupyter-collaboration-ui=2.1.0=pyhe01879c_0
  - jupyter-docprovider=2.1.0=pyhe01879c_0
  - jupyter-lsp=2.2.6=pyhe01879c_0
  - jupyter-server-mathjax=0.2.6=pyhbbac1ac_2
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.12.0=py312h06a4308_1
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_fileid=0.9.2=pyhd8ed1ab_1
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyter_server_ydoc=2.1.0=pyhe01879c_0
  - jupyter_ydoc=3.1.0=pyhe01879c_0
  - jupyterlab=4.4.6=pyhd8ed1ab_0
  - jupyterlab-git=0.51.2=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - kiwisolver=1.4.9=py312h0a2e395_0
  - krb5=1.21.3=h723845a_4
  - lark=1.2.2=pyhd8ed1ab_1
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h0aef613_1
  - libarchive=3.8.1=gpl_h98cc613_100
  - libblas=3.9.0=39_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcblas=3.9.0=39_h0358290_openblas
  - libclang-cpp20.1=20.1.8=default_hddf928d_0
  - libclang13=20.1.8=default_ha444ac7_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=hc1efc7f_1
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgfortran=15.1.0=h69a702a_4
  - libgfortran5=15.1.0=hcea5267_4
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.3=hf39c6af_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_4
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libkrb5=1.21.3=h520c7b4_4
  - liblapack=3.9.0=39_h47877c9_openblas
  - libllvm20=20.1.8=hecd9e04_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmamba=2.3.1=hae34dd5_1
  - libmambapy=2.3.1=py312ha9ff5c7_1
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=17.6=h3675c94_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsolv=0.7.35=h9463b59_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libtiff=4.7.0=h8261f1e_6
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.8=h04c0eec_1
  - libxslt=1.1.43=h7a3aeb2_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - mamba=2.3.1=hf857f84_1
  - markdown-it-py=2.2.0=py312h06a4308_1
  - markupsafe=3.0.2=py312h178313f_1
  - matplotlib=3.10.5=py312h7900ff3_0
  - matplotlib-base=3.10.5=py312he3d6523_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.0=py312h06a4308_0
  - menuinst=2.3.0=py312h06a4308_0
  - mistune=3.1.3=pyh29332c3_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert=7.16.6=hb482800_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbconvert-pandoc=7.16.6=hed9df3c_0
  - nbdime=4.0.2=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.11.3=he02047a_1
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=2.3.2=py312hf476fde_1
  - openjpeg=2.5.3=h55fea9a_1
  - openldap=2.6.10=he9288cc_1
  - openssl=3.5.2=h26f9b46_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=24.2=py312h06a4308_0
  - pandas=2.3.2=py312hf79963d_0
  - pandoc=3.2=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.45=hc749103_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py312h80c1187_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.3.7=py312h06a4308_0
  - pluggy=1.5.0=py312h06a4308_0
  - prometheus_client=0.22.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py312h4c3975b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py312h5eee18b_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pycrdt=0.12.22=py312h12e396e_0
  - pycrdt-websocket=0.15.5=pyhd8ed1ab_0
  - pydantic=2.11.7=py312h06a4308_0
  - pydantic-core=2.33.2=py312hc6f7160_0
  - pygments=2.19.1=py312h06a4308_0
  - pyodbc=5.2.0=py312h2ec8cdc_0
  - pyparsing=3.2.3=pyhe01879c_2
  - pyside6=6.9.1=py312hdb827e4_0
  - pysocks=1.7.1=py312h06a4308_1
  - pysqlite3=0.5.4=py313hb2a9d6d_0
  - python=3.12.11=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h178313f_2
  - pyzmq=27.0.2=py312hbd2df5a_1
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.1=h6ac528c_2
  - readline=8.2=h5eee18b_0
  - referencing=0.36.2=pyh29332c3_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.4=py312h06a4308_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rich=13.9.4=py312h06a4308_0
  - rpds-py=0.27.0=py312h868fb18_0
  - ruamel.yaml=0.18.10=py312h5eee18b_0
  - ruamel.yaml.clib=0.2.12=py312h5eee18b_0
  - scikit-learn=1.7.1=py312h4f0b9e3_0
  - scipy=1.16.1=py312h4ebe9ca_0
  - seaborn=0.13.2=py312h06a4308_3
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=78.1.1=py312h06a4308_0
  - simdjson=3.13.0=h84d6215_0
  - six=1.17.0=pyhe01879c_1
  - smmap=5.0.2=pyhd8ed1ab_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.7=pyhd8ed1ab_0
  - spdlog=1.15.3=h6dc744f_1
  - sqlite=3.50.4=hbc0de68_0
  - sqlite-anyio=0.2.3=pyhaa4b35c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - terminado=0.18.1=pyh0d859eb_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - tomli=2.2.1=pyhe01879c_2
  - tornado=6.5.2=py312h4c3975b_0
  - tqdm=4.67.1=py312h7040dfc_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - truststore=0.10.0=py312h06a4308_0
  - types-python-dateutil=2.9.0.20250822=pyhd8ed1ab_0
  - typing-extensions=4.12.2=py312h06a4308_0
  - typing-inspection=0.4.0=py312h06a4308_0
  - typing_extensions=4.12.2=py312h06a4308_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=16.0.0=py312h66e93f0_0
  - unixodbc=2.3.12=h661eb56_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=py312h06a4308_0
  - wayland=1.24.0=h3e06ad9_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=py312h06a4308_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - yaml-cpp=0.8.0=h6a678d5_1
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py312h4c3975b_3
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - boto3==1.40.16
      - botocore==1.40.16
      - curl-cffi==0.13.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.3.0
      - jeepney==0.9.0
      - jmespath==1.0.1
      - keyring==25.6.0
      - more-itertools==10.7.0
      - multitasking==0.0.12
      - nuvolos-odbc==0.5.1
      - nvidia-nccl-cu12==2.28.9
      - peewee==3.18.3
      - pip==25.2
      - protobuf==6.33.1
      - pyarrow==21.0.0
      - s3transfer==0.13.1
      - secretstorage==3.3.3
      - websockets==15.0.1
      - xgboost==3.1.2
      - yfinance==0.2.66
prefix: /opt/conda
